
.PHONY: all

all: 
	make -C sample01
	make -C simple_rsa
	make -C crt_rsa
	make -C diffie_hellman

clean:
	make -C sample01 clean
	make -C simple_rsa clean
	make -C crt_rsa clean
	make -C diffie_hellman clean
